### ISSUE TITLE
Doppler not sending logs to syslog when syslog_daemon_config properties are present

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/loggregator#209]
cf-release: v250
BOSH cli version: 1.3262.24.0
BOSH version: 260.1

cf manifest syslog_daemon_config settings:

```yaml
  syslog_daemon_config:
    address: 12.34.56.7
    port: 514
    transport: tcp
    #enable: true is defined in the metron_agent spec
```

I believe the problem is in doppler.json.erb:

```erb
        if_p("syslog_daemon_config") do |_|
            a[:Syslog] = "vcap.doppler"
        end
```

Unless I am mistaken, the 'if_p' function will only evaluate explicit properties such as syslog_daemon_config.enable

Thank you,
Jon Price
Intel Corporation
