### ISSUE TITLE
loggregator.bosh-lite.com Not Found

### ISSUE THREAD

**Issue by kmj940101** [cloudfoundry/loggregator#231]
I deployed CF 251 and tried to access "wss://loggregator.bosh-lite.com:443" 

It says "loggregator.bosh-lite.com Not Found"

Everything worked fine with CF 238.

When I took a look at my 251 yml, the loggregator uri was missing.

How should I change the 251 version of my yml to access loggregator?

Here is my CF 238 yml file.

```
- instances: 1
  name: loggregator_trafficcontroller_z1
  networks:
  - name: cf1
  properties:
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: doppler
        port: 8081
        registration_interval: 20s
        uris:
        - doppler.bosh-lite.com
      - name: loggregator 
        port: 8080
        registration_interval: 20s
        uris:
        - loggregator.bosh-lite.com
    traffic_controller:
      zone: z1
  resource_pool: small_z1
```

Here is my CF 251 yml file.

```
- instances: 1
  name: loggregator_trafficcontroller_z1
  networks:
  - name: cf1
  properties:
    prometheus:
      influxdb:
        url: 10.10.18.55:9008
        database: cf_metric_db
        user: admin
        pass: admin
      listen_addr: 127.0.0.1:9999
      service_name: loggregator_trafficcontroller_z1
      agent_type: cf
    node_exporter:
      listen_addr: 127.0.0.1:9100
    consul:
      agent:
        services:
          loggregator_trafficcontroller: {}
    loggregator:
      uaa:
        client_secret: doppler-secret
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: doppler
        port: 8081
        registration_interval: 20s
        uris:
        - doppler.bosh-lite.com
    traffic_controller:
      zone: z1
```
